### ISSUE TITLE
On `pdf.flatten()` check mark getting removed from flattened pdf

### ISSUE THREAD

**Issue by satyajitnayk** [cantoo-scribe/pdf-lib#41]
### What were you trying to do?

When I try to flatten a pdf with checked check box, the flattened pdf is missing check mark in check boxes.

### Visuals
|original pdf | flattened pdf |
|---------|-----------|
|<img width="565" alt="image" src="https://github.com/cantoo-scribe/pdf-lib/assets/32722867/a7113bde-4e2b-4900-9930-c6f977ed2939"> | <img width="558" alt="image" src="https://github.com/cantoo-scribe/pdf-lib/assets/32722867/35c6cd44-ff90-4922-b6a4-5abbe025d13d">|

### How did you attempt to do it?

Tried with simple script using the file [form_to_flatten.pdf](https://github.com/cantoo-scribe/pdf-lib/files/13681605/form_to_flatten.pdf)

```js
import fs from 'fs';
import { PDFDocument } from 'pdf-lib';

const flattenPDF = async () => {
  const pdfDocument = await PDFDocument.load(
    fs.readFileSync('form_to_flatten.pdf')
  );
  const pdfForm = pdfDocument.getForm();

  pdfForm.flatten();
  const pdfBytes = await pdfDocument.save();

  fs.writeFileSync('flattened.pdf', pdfBytes);
};

flattenPDF();
```

### What actually happened?

 the flattened pdf is missing check mark in check boxes.

### What did you expect to happen?

 the flattened pdf should not have missing check mark in check boxes.
 They should be intact.

### How can we reproduce the issue?

we can reproduce this using pdf & script provided in `How did you attempt to do it?` section.

### Version

1.17.1

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

Thoughts @Sharcoux @MatheusrdSantos  !!

**Comment by satyajitnayk** [comment]
This could be possibly happening  

1. `mac preview` & other pdf editing apps converts pdf version 1.7 to 1.3 to make it backward compatible when we edit an PDF [Apple Discussion Link](https://discussions.apple.com/thread/5632278?sortBy=best)
2. Apps modify the metadata of pdf's which resulting in this behavior. (Refer to screenshot)
<img width="1417" alt="image" src="https://github.com/cantoo-scribe/pdf-lib/assets/32722867/ad10ec78-e8e8-4d16-a3cd-d3e5a4e8f41d">

**Comment by Sharcoux** [comment]
@satyajitnayk We don't use this feature, so I'm not sure that we will take the time to work on this. If someone could have a look and make a PR, that would be great.

**Comment by Sharcoux** [comment]
Solved in https://github.com/cantoo-scribe/pdf-lib/pull/56 and released in v2.1.6

**Comment by satyajitnayk** [comment]
@Sharcoux #56 does not fix the issue. Check marks & radio buttons still getting removed.
<img width="629" alt="image" src="https://github.com/cantoo-scribe/pdf-lib/assets/32722867/0cd787dc-5f2c-4a68-a521-6d4711725e4a">

**Comment by RippleRurigaki** [comment]
@satyajitnayk 

My confirmation is that the check and radio buttons do show up.

![image](https://github.com/cantoo-scribe/pdf-lib/assets/31793119/b0caaa4e-dbfe-4bdf-859b-ffff132610a6)

> mac preview & other pdf editing apps converts pdf version 1.7 to 1.3/other lower versions to make it backward compatible when we edit an PDF [Apple Discussion Link](https://discussions.apple.com/thread/5632278?sortBy=best)

Are you on Version 1.3 as you commen?

I don't know what is causing this,
If you can provide us with the version 1.3 file,
I will try to find out.

**Comment by Sharcoux** [comment]
Without new information, I will close this Issue in a week.
